set(MODULE_PATH
        ${CMAKE_CURRENT_SOURCE_DIR}/shiva/math)

set(MODULE_PUBLIC_HEADERS
        ""
        )

set(MODULE_PRIVATE_HEADERS
        "")

set(MODULE_SOURCES
        ${MODULE_PUBLIC_HEADERS}
        ${MODULE_PRIVATE_HEADERS})